### PR TITLE
added DS implemented in  JS

### PR DESCRIPTION
**Pull request by sauravmankotia**
# JavaScript Data Structures

This PR contains JavaScript implementations of common data structures, each in its respective file. Below, I provide an overview of each data structure along with its intended usage, along with example code and explanations.

## 1. Linked List (`linked_list.js`)

A singly linked list is a linear data structure consisting of nodes, where each node points to the next node in the sequence.

**Usage:**
- Create a linked list.
- Append elements to the end of the list.
- Display the elements in the list.

## 2. Stack (`stack.js`)

A stack is a linear data structure that follows the Last-In, First-Out (LIFO) principle, where the most recently added element is removed first.

**Usage:**
- Create a stack.
- Push elements onto the stack.
- Pop elements from the stack.
- Peek at the top element.
- Check if the stack is empty.
- Get the size of the stack.

## 3. Queue (`queue.js`)

A queue is a linear data structure that follows the First-In, First-Out (FIFO) principle, where the first element added is the first one to be removed.

**Usage:**
- Create a queue.
- Enqueue elements into the queue.
- Dequeue elements from the queue.
- Check if the queue is empty.
- Get the size of the queue.

## 4. Binary Tree (`binary_tree.js`)

A binary tree is a hierarchical data structure where each node has at most two children: a left child and a right child.

**Usage:**
- Create a binary tree.
- Print the tree using preorder, inorder, or postorder traversal.

These JavaScript programs provide implementations of fundamental data structures and demonstrate their usage with examples. Feel free to explore and utilize these data structures for your own projects and learning purposes.

### CODE REVIEW

**Comment by sauravmankotia** [comment]
hey @wasibhussain , how come your repository is excluded from hacktoberfest??

**Comment by sauravmankotia** [comment]
what is the problem ? can you do anything to fix it??
\

**Comment by wasibhussain** [comment]
@sauravmankotia i don't know, maybe your code doesn't meet the hacktoberfest community standards.. you can check the rules on their official website.

**Comment by sauravmankotia** [comment]
Its not about my code. Its about the repository . You repository is
excluded from their.

**Pull request merged**
