### PR TITLE
image classifier in python

### PR DESCRIPTION
**Pull request by vishesh-hue**
Before running this code, make sure to replace "path_to_your_image.jpg" with the path to the image you want to classify.

This program uses a pre-trained MobileNetV2 model to classify the image into one of a thousand possible categories. It loads the image, preprocesses it, and then uses the model to make predictions. Finally, it prints the top 5 predictions with their associated confidence scores.

### CODE REVIEW

**Comment by wasibhussain** [comment]
@vishesh-hue please provide screenshot of running code.

**Comment by vishesh-hue** [comment]
Screenshot 2023-10-04 122501

**Comment by vishesh-hue** [comment]
will this commit count in hacktoberfest

**Comment by wasibhussain** [comment]
@vishesh-hue I'm merging your PR, hope it should be also accepted by hactoberfest community.

**Pull request merged**
